export const surpriseMePrompts = [
  'Bức ảnh về một chú mèo dễ thương',
  'Bức ảnh về một cảnh hoàng hôn tuyệt đẹp',
  'Bức ảnh về một khu vườn hoa rực rỡ màu sắc',
  'Bức ảnh về một con chim đang bay lượn trong bầu trời',
  'Bức ảnh về một bãi biển trong xanh và cát trắng',
  'Bức ảnh về một đám mây hình thành những hình dạng thú vị',
  'Bức ảnh về một ngọn núi cao tráng lệ với tuyết trắng phủ đỉnh',
  'Bức ảnh về một cánh đồng hoa oải hương tím mùi thơm',
  'Bức ảnh về một đàn chim hồng hạc bay lượn trên hồ',
  'Bức ảnh về một bình hoa hồng đỏ rực nở rộ',
  'Bức ảnh về một cặp tình nhân đi dạo trên bãi cát',
  'Bức ảnh về một khu rừng xanh tươi với ánh sáng mặt trời chiếu xuyên qua nhánh cây',
  'Bức ảnh về một bầu trời đêm đầy sao lấp lánh',
  'Bức ảnh về một con chó vui đùa trong công viên',
  'Bức ảnh về một bông hoa sen nở rộ trên mặt nước',
  'Bức ảnh về một tòa nhà kiến trúc độc đáo với gam màu sắc tươi sáng',
  'Bức ảnh về một cảnh sông uốn lượn xanh mát',
  'Bức ảnh về một cánh đồng lúa vàng trải dài đến tận chân trời',
  'Bức ảnh về một ngọn núi đá phong cảnh hùng vĩ',
  'Bức ảnh về một bóng hoàng hôn tạo ra những bức silhouettes đẹp mắt',
  'Bức ảnh về một bình hoa tulip đa sắc',
  'Bức ảnh về một cặp chim én đang xây tổ',
  'Bức ảnh về một cảnh đồng cỏ xanh mướt với đàn bò chân trắng',
  'Bức ảnh về một chiếc thuyền buồm trên biển xa xôi',
  'Bức ảnh về một con hươu cao cổ đứng trong cánh đồng',
  'Bức ảnh về một khu vườn Nhật Bản với cây anh đào nở rộ',
  'Bức ảnh về một cặp tình nhân ngắm hoàng hôn trên đồi cỏ',
  'Bức ảnh về một cánh đồng hoa cúc trắng trải dài',
  'Bức ảnh về một chú voi con chơi đùa trong cát',
  'Bức ảnh về một ngọn thác nước cao phun trắng xóa',
  'Bức ảnh về một đàn bướm bay lượn trong khu rừng',
  'Bức ảnh về một con hươu nhỏ màu nâu trong rừng',
  'Bức ảnh về một cặp chim đang hát hò trên cành cây',
  'Bức ảnh về một cánh đồng hoa hướng dương vàng rực',
  'Bức ảnh về một cặp tình nhân nghỉ ngơi dưới bóng cây',
  'Bức ảnh về một con hạc trắng bay trên mặt nước',
  'Bức ảnh về một ngôi làng cổ yên bình với những ngôi nhà gỗ',
  'Bức ảnh về một con chim cánh cụt đang trượt băng trên băng tuyết',
  'Bức ảnh về một cặp hươu cao cổ nhìn nhau trong đêm',
  'Bức ảnh về một bãi biển hoang sơ với cát trắng mịn',
  'Bức ảnh về một đàn bướm đủ màu sắc trên cánh đồng hoa',
];
