export const surpriseMePrompts = [
  'A photo of an adorable cat',
  'A photo of a stunning sunset',
  'A photo of a vibrant colorful flower garden',
  'A photo of a bird soaring through the sky',
  'A photo of a pristine beach with blue water and white sand',
  'A photo of clouds forming interesting shapes',
  'A photo of a majestic snow-covered mountain peak',
  'A photo of a lavender field with a fragrant aroma',
  'A photo of a flock of flamingos flying over a lake',
  'A photo of a blooming red rose',
  'A photo of a couple strolling on the beach',
  'A photo of a lush green forest with sunlight filtering through the branches',
  'A photo of a starry night sky',
  'A photo of a playful dog in the park',
  'A photo of a blooming lotus flower on water',
  'A photo of a uniquely designed architectural building with vibrant colors',
  'A photo of a winding and refreshing green river',
  'A photo of a vast golden wheat field stretching to the horizon',
  'A photo of a majestic rocky mountain landscape',
  'A photo of a sunset casting beautiful silhouettes',
  'A photo of a multicolored tulip bouquet',
  'A photo of a pair of swallows building a nest',
  'A photo of a lush green grassy meadow with white-footed cows',
  'A photo of a sailing boat on the distant sea',
  'A photo of a giraffe standing in a field',
  'A photo of a Japanese garden with blooming cherry blossoms',
  'A photo of a couple admiring the sunset on a grassy hill',
  'A photo of a vast field of white daisies',
  'A photo of a playful baby elephant in the sand',
  'A photo of a tall waterfall cascading down in white',
  'A photo of a flock of butterflies fluttering in the forest',
  'A photo of a small brown deer in the woods',
  'A photo of a pair of birds singing on a branch',
  'A photo of a sunflower field shining bright yellow',
  'A photo of a couple resting under the shade of a tree',
  'A photo of a white swan gliding on the water',
  'A photo of a serene ancient village with wooden houses',
  'A photo of a penguin sliding on the snow',
  'A photo of a pair of giraffes gazing at each other in the night',
  'A photo of an untouched beach with smooth white sand',
  'A photo of a colorful butterfly swarm over a flower field',
];
